version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: BE_mysql_${APP_NAME}
    volumes:
      - ../docker/mysql/db:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root_password"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:6.2.6-alpine
    container_name: BE_redis_${APP_NAME}
    volumes:
      - ../docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: BE_phpmyadmin_${APP_NAME}
    environment:
      - "PMA_HOST=mysql"
      - "MYSQL_ROOT_PASSWORD=root_password"
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network
  php:
    build:
      context: ../docker/php
      dockerfile: Dockerfile
    container_name: BE_php_${APP_NAME}
    environment:
      - TZ=$TZ
    ports:
      - "8001:8000"
      - "8002:8001"
    volumes:
      - ../backend:/var/www/html
      - ../docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
  composer:
    image: composer:2.3.7
    container_name: BE_composer_${APP_NAME}
    command: tail -f /dev/null
    volumes:
      - ../backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

  npm:
    image: node:18.15-alpine
    container_name: BE_npm_${APP_NAME}
    command: tail -f /dev/null
    volumes:
      - ../backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
  nginx:
    image: nginx:stable-alpine
    container_name: BE_nginx_${APP_NAME}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERT_PASS=test
      - TZ=$TZ
    volumes:
      - ../backend:/var/www/html
      - ../docker/nginx/cert.pem:/var/www/html/nginx/certs/cert.pem
      - ../docker/nginx/key.pem:/var/www/html/nginx/certs/key.pem
      - ../docker/nginx/env.conf:/var/www/html/nginx/env.conf
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../docker/nginx/log:/var/log/nginx
    depends_on:
      - php
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
